### ISSUE TITLE
Why  Lempel-Ziv Complexity '1001111011000010' is 6 but not 8?

### ISSUE THREAD

**Issue by odats** [Naereen/Lempel-Ziv_Complexity#5]
>>> from lempel_ziv_complexity import lempel_ziv_complexity
>>> s = '1001111011000010'
>>> lempel_ziv_complexity(s)  # 1 / 0 / 01 / 1110 / 1100 / 0010

1/0/01/11/10/110/00/010/ (8 unique words)

Why 6 not 8?

**Comment by Naereen** [comment]
Hi @odats,
You're perfectly right, I just realized that my implementations (in both Python/Cython and Julia) are completely wrong.

I am in the process of implementing a naive version using a list/set/dict to store the sub-strings (I have no idea how to fix the "smart" algorithm that wasn't storing them), and testing which is the fastest version.

**Comment by Naereen** [comment]
I wrote a naive version, and apparently… it's faster to use a list than not…

```
In [21]: %timeit lempel_ziv_complexity(random_string(10000))
4.86 s ± 657 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [22]: %timeit lempel_ziv_complexity_slow(random_string(10000))
8.17 ms ± 2.76 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

`lempel_ziv_complexity_slow` is the new version.

**Comment by Naereen** [comment]
I fixed the implementation, a new release is on Pypi.
Thanks for noticing the bug!

**Comment by pranaysy** [comment]
> > > > from lempel_ziv_complexity import lempel_ziv_complexity
> > > > s = '1001111011000010'
> > > > lempel_ziv_complexity(s)  **# 1 / 0 / 01 / 1110 / 1100 / 0010**
> 
> 1/0/01/11/10/110/00/010/ (8 unique words)
> 
> Why 6 not 8?

Hi @Naereen 

Isn't 6 here in the example correct?

I cross checked the decomposition using [this MATLAB implementation](https://uk.mathworks.com/matlabcentral/fileexchange/38211-calc_lz_complexity?s_tid=prof_contriblnk) - the decomposition matches the one in the comment with 6 substrings. 

I've been relying on your Cython version extensively for its speed :)
Thank you for your really cool work!

Best,
Pranay

**Comment by Naereen** [comment]
Hi @pranaysy,
Honestly I don't know.
I never read the research paper introducing Lempel-Ziv complexity, and the discussion in the comment you mentioned convinced me to update my implementation, and thus finding 8 instead of 6 in this example.
I saw the discussion on https://github.com/raphaelvallat/entropy/issues/14#issuecomment-771826542, but I don't have time until next Tuesday to look into it in details, sorry.

**Comment by pranaysy** [comment]
Hi @Naereen 

Thank you for your prompt response

I understand, I'll probably have some time over the weekend to go through your code. I'll post updates here, if any :)
