### ISSUE TITLE
ModuleNotFoundError: No module named 'lempel_ziv_complexity'

### ISSUE THREAD

**Issue by odats** [Naereen/Lempel-Ziv_Complexity#6]
<img width="970" alt="Screenshot 2019-12-19 at 13 14 08" src="https://user-images.githubusercontent.com/944379/71169400-806caf80-2261-11ea-94f7-7179a7c05845.png">

**Comment by Naereen** [comment]
(just so you know, it is usually nice to say "hello" etc, not just copy-paste an error message…)

**Comment by Naereen** [comment]
I don't know where you are trying this, but I guess the issue is because you use naively `!pip install` from the Jupyter notebook.
See https://jakevdp.github.io/blog/2017/12/05/installing-python-packages-from-jupyter/#How-to-use-Pip-from-the-Jupyter-Notebook

**Comment by odats** [comment]
Hello Naereen,
I have tried suggested solution but still getting error. (google colab)

<img width="884" alt="Screenshot 2019-12-19 at 14 33 21" src="https://user-images.githubusercontent.com/944379/71173963-b4010700-226c-11ea-8dec-f2dd99df269c.png">

**Comment by Naereen** [comment]
You're right, it's crazy, apparently the package I upload to Pypi is empty… I don't get it.
(this project is old and I never tested it or used it since I wrote it)

**Comment by Naereen** [comment]
It should be fixed now, sorry!
https://pypi.org/project/lempel-ziv-complexity/

**Comment by odats** [comment]
Thank you, it works now. You did a good job.

**Comment by Naereen** [comment]
Thanks!
